-- ALTER TABLE articles
-- ADD COLUMN is_accepted BOOLEAN DEFAULT NULL;

-- ALTER TABLE career_request
-- ADD COLUMN is_reviewed BOOLEAN DEFAULT FALSE NOT NULL;

ALTER TABLE articles
ADD COLUMN slug VARCHAR(255) UNIQUE;

